#!/bin/bash

curdir=$(dirname $0)


if [ "${CI_REGISTRY}" = "dev.gitlab.org:5005" ]
then
  group_name="gitlab"
  if ${curdir}/is_gitlab_ee.sh
  then
    assets_image="${group_name}/gitlab-ee/gitlab-assets-ee"
  else
    assets_image="${group_name}/gitlabhq/gitlabhq-assets"
  fi
else
  group_name="gitlab-org"
  if ${curdir}/is_gitlab_ee.sh
  then
    assets_image="${group_name}/gitlab-ee/gitlab-assets-ee"
  else
    assets_image="${group_name}/gitlab-ce/gitlab-assets-ce"
  fi
fi

gitlab_version=$(cat VERSION | awk '
  {
    gsub(/[^a-z0-9]/, "-")
    gsub(/(\A-+|-+\z)/, "")
    print substr($0, 1, 63);
  }
')

docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
docker create --name asset_cache ${CI_REGISTRY}/${assets_image}:${gitlab_version}
docker cp asset_cache:/assets ${ASSET_PATH}
