#!/bin/bash

curdir=$(dirname $0)


if [ "${CI_REGISTRY}" = "dev.gitlab.org:5005" ]
then
  group_name="gitlab"
  if ${curdir}/is_gitlab_ee.sh
  then
    assets_image="${group_name}/gitlab-ee/gitlab-assets-ee"
  else
    assets_image="${group_name}/gitlabhq/gitlabhq-assets"
  fi
else
  group_name="gitlab-org"
  if ${curdir}/is_gitlab_ee.sh
  then
    assets_image="${group_name}/gitlab-ee/gitlab-assets-ee"
  else
    assets_image="${group_name}/gitlab-ce/gitlab-assets-ce"
  fi
fi

echo ${CI_REGISTRY}/${assets_image}
