#!/bin/bash


curdir=$(dirname $0)

if ${curdir}/is_gitlab_ee.sh
then
  project_name="gitlab-ee"
else
  if [ "${CI_REGISTRY}" = "registry.gitlab.com" ]
  then
    project_name="gitlab-ce"
  else
    project_name="gitlabhq"
  fi
fi

echo ${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/${project_name}/${project_name}-assets
