.TH "GITLAB " "1" " Container Image Page" "GitLab Inc" "November 22, 2016" 
.nh
.ad l


.SH DESCRIPTION
.PP
The GitLab Container images are monolithic images of GitLab running all the necessary services on a single container.

.PP
More information about the images can be found at 
\[la]https://docs.gitlab.com/omnibus/docker/README.html\[ra]


.SH HISTORY
.PP
8.14.0
Initial release
