#!/bin/bash

set -xe

source /OS_RELEASE
source /RELEASE

ubuntu_install ()
{
  echo "deb https://packages.gitlab.com/gitlab/${PACKAGECLOUD_REPO}/ubuntu/ ${OS_DISTRIBUTION} main" > /etc/apt/sources.list.d/gitlab_${RELEASE_PACKAGE}.list
  wget -q -O - https://packages.gitlab.com/gpg.key | apt-key add -
  apt-get update
  apt-get install -yq --no-install-recommends ${RELEASE_PACKAGE}=${RELEASE_VERSION}
}

rhel_install ()
{
  cat > /etc/yum.repos.d/gitlab_${RELEASE_PACKAGE}.repo << EOL
[gitlab_gitlab-ee]
name=gitlab_gitlab-ee
baseurl=https://packages.gitlab.com/gitlab/${PACKAGECLOUD_REPO}/el/${OS_DISTRIBUTION}/x86_64
repo_gpgcheck=1
gpgcheck=0
enabled=1
gpgkey=https://packages.gitlab.com/gitlab/gitlab-ee/gpgkey
sslverify=1
sslcacert=/etc/pki/tls/certs/ca-bundle.crt
metadata_expire=300
EOL
  yum install -y ${RELEASE_PACKAGE}-${RELEASE_VERSION}.el${OS_DISTRIBUTION}.x86_64
  yum clean all
}

if [ "${OS_ID}" = "ubuntu" ]; then
  ubuntu_install
elif [ "${OS_ID}" = "rhel" ]; then
  rhel_install
else
  echo 'OS not yet supported for building the GitLab docker image'
fi
