#!/bin/bash

set -e

source /etc/lsb-release
source /RELEASE
source /assets/.env

# Remove sensitive content from RELEASE file. We can't remove the file because
# we are using it in assets/wrapper.
sed -i "/DOWNLOAD_URL/d;/TRIGGER_PRIVATE_TOKEN/d;" /RELEASE

# Install GitLab
DOWNLOAD_URL=${DOWNLOAD_URL} TRIGGER_PRIVATE_TOKEN=${TRIGGER_PRIVATE_TOKEN} /assets/download-package && dpkg -i /tmp/gitlab.deb && rm /tmp/gitlab.deb
rm -rf /var/lib/apt/lists/*

unset DOWNLOAD_URL
unset TRIGGER_PRIVATE_TOKEN

# Create sshd daemon
mkdir -p /opt/gitlab/sv/sshd/supervise /opt/gitlab/sv/sshd/log/supervise
mkfifo /opt/gitlab/sv/sshd/supervise/ok /opt/gitlab/sv/sshd/log/supervise/ok
printf "#!/bin/sh\nexec 2>&1\numask 077\nexec /usr/sbin/sshd -D -f /assets/sshd_config -e" > /opt/gitlab/sv/sshd/run
printf "#!/bin/sh\nexec svlogd -tt /var/log/gitlab/sshd" > /opt/gitlab/sv/sshd/log/run
chmod a+x /opt/gitlab/sv/sshd/run /opt/gitlab/sv/sshd/log/run

# Remove current gitlab.rb file
rm -f /etc/gitlab/gitlab.rb

# Patch omnibus package
sed -i "s/external_url 'GENERATED_EXTERNAL_URL'/# external_url 'GENERATED_EXTERNAL_URL'/" /opt/gitlab/etc/gitlab.rb.template
sed -i "s/\/etc\/gitlab\/gitlab.rb/\/assets\/gitlab.rb/" /opt/gitlab/embedded/cookbooks/gitlab/recipes/show_config.rb
sed -i "s/\/etc\/gitlab\/gitlab.rb/\/assets\/gitlab.rb/" /opt/gitlab/embedded/cookbooks/gitlab/recipes/config.rb

# Set install type to docker
echo 'gitlab-docker' > /opt/gitlab/embedded/service/gitlab-rails/INSTALLATION_TYPE

# Create groups
groupadd -g ${GITLAB_GIT_GID} git
groupadd -g ${GITLAB_WWW_GID} gitlab-www
groupadd -g ${GITLAB_REDIS_GID} gitlab-redis
groupadd -g ${GITLAB_POSTGRES_GID} gitlab-psql

groupadd -g ${GITLAB_MATTERMOST_GID} mattermost
groupadd -g ${GITLAB_REGISTRY_GID} registry
groupadd -g ${GITLAB_PROMETHEUS_GID} gitlab-prometheus
groupadd -g ${GITLAB_CONSUL_GID} gitlab-consul

# Create accounts
## The git account is created with * as crypted password as ssh treats the account as locked if it has a ! 
## Issue #5891 https://gitlab.com/gitlab-org/omnibus-gitlab
useradd -m -u ${GITLAB_GIT_UID} -g git -p '*' -m -s /bin/sh -d /var/opt/gitlab git
useradd -m -u ${GITLAB_WWW_UID} -g gitlab-www -m -s /bin/false -d /var/opt/gitlab/nginx gitlab-www
useradd -m -u ${GITLAB_REDIS_UID} -g gitlab-redis -m -s /bin/false -d /var/opt/gitlab/redis gitlab-redis
useradd -m -u ${GITLAB_POSTGRES_UID} -g gitlab-psql -m -s /bin/sh -d /var/opt/gitlab/postgresql gitlab-psql
useradd -m -u ${GITLAB_MATTERMOST_UID} -g mattermost -m -s /bin/sh -d /var/opt/gitlab/mattermost mattermost
useradd -m -u ${GITLAB_REGISTRY_UID} -g registry -m -s /bin/sh -d /var/opt/gitlab/registry registry
useradd -m -u ${GITLAB_PROMETHEUS_UID} -g gitlab-prometheus -m -s /bin/sh -d /var/opt/gitlab/prometheus gitlab-prometheus
useradd -m -u ${GITLAB_CONSUL_UID} -g gitlab-consul -m -s /bin/sh -d /var/opt/gitlab/consul gitlab-consul
