#!/bin/bash

set -xe

if [ -e /etc/lsb-release ]; then
  source /etc/lsb-release
  os=${DISTRIB_ID}
  dist=${DISTRIB_CODENAME}
elif [ -e /etc/os-release ]; then
  source /etc/os-release
  os=${ID}
  dist=`echo ${VERSION_ID} | awk -F '.' '{ print $1 }'`
else
  echo 'OS not detected'
fi

echo "OS_ID=${os}" >> /OS_RELEASE
echo "OS_DISTRIBUTION=${dist}" >> /OS_RELEASE

# Install the GitLab package
/assets/install

# Create sshd daemon
mkdir -p /opt/gitlab/sv/sshd/supervise /opt/gitlab/sv/sshd/log/supervise
mkfifo /opt/gitlab/sv/sshd/supervise/ok /opt/gitlab/sv/sshd/log/supervise/ok
printf "#!/bin/sh\nexec 2>&1\numask 077\nexec /usr/sbin/sshd -D -f /assets/sshd_config -e" > /opt/gitlab/sv/sshd/run
printf "#!/bin/sh\nexec svlogd -tt /var/log/gitlab/sshd" > /opt/gitlab/sv/sshd/log/run
chmod a+x /opt/gitlab/sv/sshd/run /opt/gitlab/sv/sshd/log/run
mkdir -p /var/run/sshd

# Remove current gitlab.rb file
rm -f /etc/gitlab/gitlab.rb

# Patch omnibus package
patch -p0 -d /opt/gitlab < /assets/gitlab-rb-location.patch

/assets/create-accounts
