#!/bin/bash

set -x

source /assets/.env

# chown_if_exists
# input: matches `chown` command, see `man chown`
# Simply, this checks that the file you're trying to chown actually exists
# before making the chown call. DRY'ing the rest of this script's checks.
chown_if_exists()
{
	# the last argument of chown is the file or path
	path="${@:${#@}}"
	if [ -e "$path" ]; then
		chown $@
	else
		echo "skipping, path does not exist: $path"
	fi
}

chmod_if_exists()
{
	# the last argument of chown is the file or path
	path="${@:${#@}}"
	if [ -e "$path" ]; then
		chmod $@
	else
		echo "skipping, path does not exist: $path"
	fi
}

# Fix GitLab permissions
if id -u git; then
	# Fix data storage
	chown_if_exists -R ${GITLAB_GIT_UID}:${GITLAB_GIT_GID} /var/opt/gitlab/.ssh
	chown_if_exists -R ${GITLAB_GIT_UID}:${GITLAB_GIT_GID} /var/opt/gitlab/.gitconfig
	chown_if_exists -R ${GITLAB_GIT_UID}:${GITLAB_GIT_GID} /var/opt/gitlab/git-data
	chmod_if_exists 2770 /var/opt/gitlab/git-data/repositories
	chown_if_exists -R ${GITLAB_GIT_UID}:${GITLAB_GIT_GID} /var/opt/gitlab/gitaly
	chown_if_exists -R ${GITLAB_GIT_UID}:${GITLAB_GIT_GID} /var/opt/gitlab/gitlab-ci/builds
	chown_if_exists -R ${GITLAB_GIT_UID}:${GITLAB_GIT_GID} /var/opt/gitlab/gitlab-rails
	chown_if_exists -R ${GITLAB_GIT_UID}:${GITLAB_GIT_GID} /var/opt/gitlab/gitlab-shell
	chown_if_exists -R ${GITLAB_GIT_UID} /var/opt/gitlab/gitlab-ci
	chown_if_exists -R ${GITLAB_GIT_UID} /var/opt/gitlab/gitlab-exporter
	if id -g gitlab-www; then
		chown_if_exists -R ${GITLAB_GIT_UID}:${GITLAB_WWW_GID} /var/opt/gitlab/gitlab-workhorse
	fi

	# Fix log storage
	chown_if_exists ${GITLAB_GIT_UID} /var/log/gitlab/gitlab-workhorse
	chown_if_exists ${GITLAB_GIT_UID} /var/log/gitlab/gitlab-rails
	chown_if_exists ${GITLAB_GIT_UID} /var/log/gitlab/gitlab-shell
	chown_if_exists ${GITLAB_GIT_UID} /var/log/gitlab/sidekiq
	chown_if_exists ${GITLAB_GIT_UID} /var/log/gitlab/puma
	chown_if_exists ${GITLAB_GIT_UID} /var/log/gitlab/unicorn
	chown_if_exists ${GITLAB_GIT_UID} /var/log/gitlab/gitaly
	chown_if_exists ${GITLAB_GIT_UID} /var/log/gitlab/gitlab-exporter

	# Update log files
	chown_if_exists -R ${GITLAB_GIT_UID}:${GITLAB_GIT_GID} /var/log/gitlab/gitlab-rails/*.log
	chown_if_exists -R ${GITLAB_GIT_UID}:${GITLAB_GIT_GID} /var/log/gitlab/gitlab-shell/*.log
	chown_if_exists -R ${GITLAB_GIT_UID}:${GITLAB_GIT_GID} /var/log/gitlab/puma/*.log
	chown_if_exists -R ${GITLAB_GIT_UID}:${GITLAB_GIT_GID} /var/log/gitlab/unicorn/*.log
	chown_if_exists -R ${GITLAB_GIT_UID}:${GITLAB_GIT_GID} /var/log/gitlab/gitaly/*.log
fi

# Fix nginx buffering directory permission
if id -u gitlab-www; then
	chown_if_exists -R ${GITLAB_WWW_UID}:${GITLAB_WWW_GID} /var/opt/gitlab/nginx/*_temp
	chown_if_exists -R ${GITLAB_WWW_UID}:${GITLAB_WWW_GID} /var/opt/gitlab/nginx/*_cache
fi

# Fix database storage and logs
if id -u gitlab-psql; then
	chown_if_exists -R ${GITLAB_POSTGRES_UID}:${GITLAB_POSTGRES_GID} /var/opt/gitlab/postgresql
	chown_if_exists ${GITLAB_POSTGRES_UID} /var/log/gitlab/postgresql
fi

# Fix prometheus storage and logs
if id -u gitlab-prometheus; then
	chown_if_exists -R ${GITLAB_PROMETHEUS_UID}:${GITLAB_PROMETHEUS_GID} /var/opt/gitlab/prometheus
	chown_if_exists ${GITLAB_PROMETHEUS_UID} /var/log/gitlab/prometheus
	chown_if_exists -R ${GITLAB_PROMETHEUS_UID}:${GITLAB_PROMETHEUS_GID} /var/opt/gitlab/alertmanager
	chown_if_exists ${GITLAB_PROMETHEUS_UID} /var/log/gitlab/alertmanager
fi

# Fix redis storage and logs
if id -u gitlab-redis; then
	chown_if_exists -R ${GITLAB_REDIS_UID}:${GITLAB_REDIS_GID} /var/opt/gitlab/redis
	if id -g git ; then
		chown_if_exists ${GITLAB_REDIS_UID}:${GITLAB_GIT_GID} /var/opt/gitlab/redis
	fi
	chown_if_exists ${GITLAB_REDIS_UID} /var/log/gitlab/redis
fi

# Fix registry storage
if id -u registry; then
    chown_if_exists -R ${GITLAB_REGISTRY_UID}:${GITLAB_GIT_GID} /var/opt/gitlab/gitlab-rails/shared/registry
fi

# Fix mattermost storage
if id -u mattermost; then
    chown_if_exists -R ${GITLAB_MATTERMOST_UID} /var/opt/gitlab/mattermost
fi
