name 'gitlab-cluster'
maintainer 'GitLab.com'
maintainer_email 'support@gitlab.com'
license 'Apache 2.0'
description 'Install and configure GitLab Cluster from Omnibus'
long_description 'Install and configure GitLab Cluster from Omnibus'
version '0.0.1'
recipe 'gitlab-cluster', 'Configures GitLab Cluster from Omnibus'

supports 'ubuntu'
supports 'centos'

depends 'package'
depends 'gitlab'
depends 'consul'
